name: run
on:
  push:
    branches: [ main ]
    paths-ignore: 'README.md'
  workflow_dispatch:

env:

  GitHubMail: "shazuxD7@gmail.com"
  GitHubName: "ShazuxD7"
  Branch: "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@main

      - name: Set Git Configs & Secrets
      - run: |
          git config --global user.email ${GitHubMail}
          git config --global user.name ${GitHubName}
          git config --global credential.helper store
          echo "https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials

      - name: cleanup
      - uses: rokibhasansagar/slimhub_actions@main

      - name: EnvSetup
      - run: |
          sudo apt install git -y &&git clone https://github.com/akhilnarang/scripts &&cd scripts &&sudo bash setup/android_build_env.sh &&rm -rf scripts
      - name: Spam Tmate
      - uses: mxschmitt/action-tmate@v3
